import type { SearchSuggestion, SearchResult } from './search.types';

// Search suggestions/autocomplete data
export const cipfaSuggestions: SearchSuggestion[] = [
  { text: 'Member FAQs' },
  { text: 'What is CIPFA' },
  { text: 'How to join CIPFA' },
  { text: 'CPD requirements' },
  { text: 'Home Truths On STPs' },
  { text: 'John Bolton - What Does Good Look Like' },
  { text: 'Better Care Fund Survey Results' },
  { text: 'Fact Or Fiction: Dispelling The Myths' },
  { text: 'Developing Leadership and skills' },
  { text: 'Building Governance and Trust' },
  { text: 'Increasing Financial Resilience' },
  { text: 'Protecting Place and Planet' },
  { text: 'CIPFA Learning' },
  { text: 'Joining CIPFA' },
  { text: 'Membership Fees' },
  { text: 'Continued Professional Development (CPD)' },
  { text: 'Accessing Your Benefits' },
  { text: 'Contacting CIPFA' },
  { text: 'Training and Events' },
  { text: 'Professional Accountancy Qualification' },
  { text: 'Public Finance Live' },
  { text: 'Counter fraud investigators' },
  { text: 'Public Sector Sustainability Certificate' },
  { text: 'Student registration' },
  { text: 'Exemptions' },
  { text: 'CIPFA exams' },
  { text: 'MyCIPFA login' },
  { text: 'Financial resilience model' },
  { text: 'Local government finance' },
];

// Search results data - CIPFA dummy content
export const cipfaSearchData: SearchResult[] = [
  {
    title: 'Member FAQs',
    description:
      'Frequently asked questions for CIPFA members covering membership benefits, CPD requirements, and member services.',
    categoryPath: ['CIPFA', 'Members', 'Member FAQs'],
    date: '2015-10-06',
    category: 'Membership',
    url: '/members/faqs',
    relevance: 10,
  },
  {
    title: 'Home Truths On STPs',
    description:
      'An in-depth analysis of Sustainability and Transformation Partnerships, examining their impact on public sector finance and service delivery.',
    categoryPath: ['CIPFA', 'CIPFA Thinks', 'Articles', 'Home truths on STPs'],
    date: '2017-12-05',
    category: 'Article',
    tags: ['Sustainability', 'Performance improvement', 'Policy'],
    url: '/articles/home-truths-stps',
    relevance: 9,
  },
  {
    title: 'John Bolton - What Does Good Look Like When There Are Scarce Resources In Social Care?',
    description:
      'Expert insights from John Bolton on effective resource management in social care settings, exploring best practices for delivering quality care with limited resources.',
    categoryPath: [
      'CIPFA',
      'CIPFA Thinks',
      'Articles',
      'John Bolton - what does good look like when there are scarce resources in social care?',
    ],
    date: '2015-11-09',
    category: 'Article',
    url: '/articles/john-bolton-social-care',
    relevance: 8,
  },
  {
    title:
      'Fact Or Fiction: Dispelling The Myths To Achieve Effective Health And Social Care Collaboration',
    description:
      'A comprehensive examination of common misconceptions about health and social care collaboration, providing evidence-based guidance for effective partnership working.',
    categoryPath: [
      'CIPFA',
      'CIPFA Thinks',
      'Articles',
      'Fact or fiction: dispelling the myths to achieve effective health and social care collaboration',
    ],
    date: '2017-05-08',
    category: 'Article',
    tags: ['Health and social care'],
    url: '/articles/fact-or-fiction-health-social-care',
    relevance: 8,
  },
  {
    title: 'Better Care Fund Survey Results',
    description:
      'Analysis of survey findings on the Better Care Fund, examining its effectiveness in supporting integrated health and social care services.',
    categoryPath: ['CIPFA', 'CIPFA Thinks', 'Articles', 'Better Care Fund survey results'],
    date: '2016-09-12',
    category: 'Article',
    url: '/articles/better-care-fund-survey',
    relevance: 7,
  },
  {
    title: 'Developing Leadership and Skills',
    description:
      "People are an organisation's most important asset. However, the people challenges faced by public sector bodies are often more complex than for other types of organisations.",
    categoryPath: ['CIPFA', 'Services', 'Training'],
    date: '2024-01-15',
    category: 'Training',
    tags: ['Leadership', 'Skills Development'],
    url: '/services/developing-leadership-skills',
    relevance: 9,
    featured: true,
  },
  {
    title: 'Building Governance and Trust',
    description:
      'Public services need to be delivered against the backdrop of an increasingly challenging macro-environment and with an increasing need for transparency and trust.',
    categoryPath: ['CIPFA', 'Services', 'Governance'],
    date: '2024-02-20',
    category: 'Service',
    tags: ['Governance', 'Trust', 'Transparency'],
    url: '/services/building-governance-trust',
    relevance: 9,
  },
  {
    title: 'Increasing Financial Resilience',
    description:
      'Public sector organisations globally need to tackle a myriad of challenges as they strive to improve their resilience and financial management.',
    categoryPath: ['CIPFA', 'Services', 'Financial Resilience'],
    date: '2024-03-10',
    category: 'Service',
    tags: ['Financial Resilience', 'Risk Management'],
    url: '/services/increasing-financial-resilience',
    relevance: 8,
  },
  {
    title: 'Protecting Place and Planet',
    description:
      'At CIPFA, we believe that improving public services is the key to improving the lives of people in their communities.',
    categoryPath: ['CIPFA', 'Services', 'Sustainability'],
    date: '2024-04-05',
    category: 'Service',
    tags: ['Sustainability', 'Community'],
    url: '/services/protecting-place-planet',
    relevance: 8,
  },
  {
    title: 'Readmission to CIPFA',
    description:
      'Members applying for re-admission are asked to confirm that they have not held themselves out to be a Member in the intervening period, why their membership lapsed and why they wish to be re-admitted, how they have maintained and developed their knowledge and skills for the previous 12 months, and that they will observe all the ethical and technical guides of the Institute.',
    categoryPath: ['CIPFA', 'Members', 'Membership'],
    date: '2024-01-01',
    category: 'Membership',
    url: '/members/readmission',
    relevance: 7,
    featured: true,
  },
  {
    title: 'CIPFA Learning',
    description:
      'Access comprehensive learning resources, course materials, and educational content for CIPFA students and members.',
    categoryPath: ['CIPFA', 'Students', 'CIPFA Learning'],
    date: '2024-05-15',
    category: 'Student Support',
    url: '/students/cipfa-learning',
    relevance: 6,
  },
  {
    title: 'Joining CIPFA',
    description:
      'Information about becoming a CIPFA member, including eligibility requirements, application process, and membership benefits.',
    categoryPath: ['CIPFA', 'Members', 'Joining CIPFA'],
    date: '2024-06-01',
    category: 'Membership',
    url: '/members/joining',
    relevance: 6,
  },
  {
    title: 'Membership Fees',
    description:
      'Details about CIPFA membership fees, payment options, and fee structures for different membership categories.',
    categoryPath: ['CIPFA', 'Members', 'Membership Fees'],
    date: '2024-06-10',
    category: 'Membership',
    url: '/members/fees',
    relevance: 5,
  },
  {
    title: 'Continued Professional Development (CPD)',
    description:
      'Guidance on CPD requirements for CIPFA members, including how to record and maintain your professional development activities.',
    categoryPath: ['CIPFA', 'Members', 'Continued Professional Development (CPD)'],
    date: '2024-07-01',
    category: 'Membership',
    url: '/members/cpd',
    relevance: 6,
  },
  {
    title: 'Accessing Your Benefits',
    description:
      'Learn about the range of benefits available to CIPFA members and how to access them, including training discounts, publications, and networking opportunities.',
    categoryPath: ['CIPFA', 'Members', 'Accessing Your Benefits'],
    date: '2024-07-15',
    category: 'Membership',
    url: '/members/benefits',
    relevance: 5,
  },
  {
    title: 'Contacting CIPFA',
    description:
      'Contact information for CIPFA, including phone numbers, email addresses, and office locations for different departments and services.',
    categoryPath: ['CIPFA', 'Customer Support', 'Contacting CIPFA'],
    date: '2024-08-01',
    category: 'Customer Support',
    url: '/contact',
    relevance: 5,
  },
  {
    title: 'Training and Events',
    description:
      'Browse CIPFA training courses, conferences, and events designed to support public finance professionals throughout their careers.',
    categoryPath: ['CIPFA', 'Training and Events'],
    date: '2024-08-15',
    category: 'Training',
    url: '/training',
    relevance: 6,
  },
  // FAQ Featured Answers
  {
    title: 'What is CIPFA?',
    faqQuestion: 'What is CIPFA?',
    description:
      'The Chartered Institute of Public Finance and Accountancy (CIPFA) is a UK-based international accountancy membership and standard-setting body. We are the only such body globally dedicated to public financial management. CIPFA believes that improving public services is the key to changing lives for the better and that good public financial management is central to achieving this ambition.',
    categoryPath: ['CIPFA', 'About us'],
    date: '2024-01-01',
    category: 'FAQ',
    url: '/about/what-is-cipfa',
    relevance: 10,
    featured: true,
    readTime: '3 minute read',
    author: 'By CIPFA Staff',
  },
  {
    title: 'How do I join CIPFA?',
    faqQuestion: 'How do I join CIPFA?',
    description:
      'To join CIPFA, you need to meet the eligibility requirements which typically include relevant qualifications and experience in public finance. You can apply online through MyCIPFA or contact our membership team. The application process involves submitting your qualifications, work experience, and references. Once approved, you will gain access to member benefits including training, publications, and networking opportunities.',
    categoryPath: ['CIPFA', 'Members', 'Joining CIPFA'],
    date: '2024-06-01',
    category: 'FAQ',
    url: '/members/joining',
    relevance: 10,
    featured: true,
    readTime: '5 minute read',
    author: 'By CIPFA Staff',
  },
  {
    title: 'What are the CPD requirements for CIPFA members?',
    faqQuestion: 'What are the CPD requirements for CIPFA members?',
    description:
      'All CIPFA members are required to complete Continuing Professional Development (CPD) activities each year. Members must complete a minimum of 20 hours of CPD annually, with at least 10 hours being verifiable. CPD activities can include attending training courses, conferences, webinars, reading professional publications, or undertaking relevant work-based learning. Members must record their CPD activities in their Learning and Development Record.',
    categoryPath: ['CIPFA', 'Members', 'CPD'],
    date: '2024-07-01',
    category: 'FAQ',
    url: '/members/cpd-requirements',
    relevance: 10,
    featured: true,
    readTime: '4 minute read',
    author: 'By CIPFA Staff',
  },
  {
    title: 'How do I access MyCIPFA?',
    faqQuestion: 'How do I access MyCIPFA?',
    description:
      'MyCIPFA is the online portal for CIPFA members and students. To access it, go to www.cipfa.org/MyCIPFA and log in with your membership number and password. If you have forgotten your login details, you can reset your password using the "Forgotten Password" link. For additional support, contact CIPFA by phone at +44 (0)20 7543 5600 or email hello@cipfa.org.',
    categoryPath: ['CIPFA', 'Members', 'MyCIPFA'],
    date: '2024-08-01',
    category: 'FAQ',
    url: '/members/mycipfa',
    relevance: 9,
    featured: true,
    readTime: '2 minute read',
    author: 'By CIPFA Staff',
  },
  // Additional Search Results
  {
    title: 'Public Finance Live 15-16 July 2026',
    description:
      'Super early bird discount until 30 January 2026. Join us for the premier public finance event of the year, featuring expert speakers, networking opportunities, and insights into the latest developments in public sector finance.',
    categoryPath: ['CIPFA', 'Training and Events', 'Conferences'],
    date: '2024-12-01',
    category: 'Event',
    tags: ['Conference', 'Networking', 'Public Finance'],
    url: '/events/public-finance-live-2026',
    relevance: 9,
    readTime: '2 minute read',
    author: 'By CIPFA Events Team',
  },
  {
    title: "Developing tomorrow's public finance leaders",
    description:
      'Supporting public finance professionals throughout their careers with world-class education and advisory services. Our training programmes help professionals add value to their teams and the organisations for which they work.',
    categoryPath: ['CIPFA', 'Services', 'Training'],
    date: '2024-11-15',
    category: 'Training',
    tags: ['Leadership', 'Education', 'Professional Development'],
    url: '/services/training',
    relevance: 9,
    readTime: '5 minute read',
    author: 'By CIPFA Staff',
  },
  {
    title: 'Create the next generation of counter fraud investigators',
    description:
      "Build expertise in governance, risk and counter fraud skills with CIPFA's professional qualifications. Our counter fraud programmes are designed to develop the skills needed to detect, prevent, and investigate fraud in public sector organisations.",
    categoryPath: ['CIPFA', 'Qualifications', 'Counter Fraud'],
    date: '2024-10-20',
    category: 'Qualification',
    tags: ['Counter Fraud', 'Governance', 'Risk Management'],
    url: '/qualifications/counter-fraud',
    relevance: 8,
    readTime: '6 minute read',
    author: 'By CIPFA Qualifications Team',
  },
  {
    title: 'ICAEW CIPFA Public Sector Sustainability Certificate',
    description:
      'Gain expertise in public sector sustainability and environmental financial management. This certificate programme provides comprehensive training on sustainability reporting, carbon accounting, and sustainable finance practices for public sector organisations.',
    categoryPath: ['CIPFA', 'Qualifications', 'Certificates'],
    date: '2024-09-10',
    category: 'Certificate',
    tags: ['Sustainability', 'Environmental Finance', 'Certification'],
    url: '/qualifications/sustainability-certificate',
    relevance: 8,
    readTime: '4 minute read',
    author: 'By CIPFA Staff',
  },
  {
    title: 'Accelerated route to qualify for CPFA and ACA designation',
    description:
      'CIPFA and ICAEW offer an accelerated route for qualified accountants to gain dual membership and both CPFA and ACA designations. This programme recognises existing qualifications and provides a streamlined path to dual professional recognition.',
    categoryPath: ['CIPFA', 'Qualifications', 'Accelerated Routes'],
    date: '2024-08-25',
    category: 'Qualification',
    tags: ['CPFA', 'ACA', 'Dual Membership'],
    url: '/qualifications/accelerated-route',
    relevance: 7,
    readTime: '5 minute read',
    author: 'By CIPFA Staff',
  },
  {
    title: 'Local Government Finance Model',
    description:
      "CIPFA's Local Government Finance Model helps local authorities understand and manage their financial position. The model provides tools and guidance for budget planning, financial forecasting, and long-term financial sustainability.",
    categoryPath: ['CIPFA', 'Services', 'Financial Models'],
    date: '2024-07-20',
    category: 'Service',
    tags: ['Local Government', 'Financial Modelling', 'Budget Planning'],
    url: '/services/local-government-finance-model',
    relevance: 8,
    readTime: '7 minute read',
    author: 'By CIPFA Advisory Team',
  },
  {
    title: 'Financial Resilience Index',
    description:
      'The CIPFA Financial Resilience Index provides a comprehensive assessment of local authority financial health. It helps councils identify areas of financial risk and develop strategies to improve their financial resilience.',
    categoryPath: ['CIPFA', 'Services', 'Financial Resilience'],
    date: '2024-06-15',
    category: 'Service',
    tags: ['Financial Resilience', 'Risk Assessment', 'Local Government'],
    url: '/services/financial-resilience-index',
    relevance: 8,
    readTime: '6 minute read',
    author: 'By CIPFA Research Team',
  },
  {
    title: 'Student Registration and MyCIPFA Access',
    description:
      'New students can register for CIPFA qualifications through our online portal. Once registered, students gain access to MyCIPFA where they can access learning materials, submit assignments, and track their progress. Student registration is now available through the upgraded system.',
    categoryPath: ['CIPFA', 'Students', 'Registration'],
    date: '2024-05-10',
    category: 'Student Support',
    tags: ['Student Registration', 'MyCIPFA', 'Learning Materials'],
    url: '/students/registration',
    relevance: 7,
    readTime: '3 minute read',
    author: 'By CIPFA Student Services',
  },
  {
    title: 'CIPFA Exams: Specimen and Technical Tests',
    description:
      'Students can access specimen tests and technical tests to prepare for CIPFA examinations. These practice tests help students understand the exam format and identify areas for further study. Exam scheduling is available through the student portal.',
    categoryPath: ['CIPFA', 'Students', 'Exams'],
    date: '2024-04-05',
    category: 'Student Support',
    tags: ['Exams', 'Specimen Tests', 'Technical Tests'],
    url: '/students/exams',
    relevance: 7,
    readTime: '4 minute read',
    author: 'By CIPFA Examinations Team',
  },
  {
    title: 'Exemptions from CIPFA Qualifications',
    description:
      'CIPFA offers exemptions from certain examination papers for students who have completed relevant qualifications or have significant relevant work experience. Exemptions are assessed on a case-by-case basis and can help accelerate your qualification journey.',
    categoryPath: ['CIPFA', 'Students', 'Exemptions'],
    date: '2024-03-20',
    category: 'Student Support',
    tags: ['Exemptions', 'Qualifications', 'Accelerated Learning'],
    url: '/students/exemptions',
    relevance: 6,
    readTime: '5 minute read',
    author: 'By CIPFA Qualifications Team',
  },
  {
    title: 'CIPFAstats: Public Sector Financial Data',
    description:
      'CIPFAstats provides comprehensive financial data and statistics for public sector organisations. Access benchmarking data, financial trends, and comparative analysis to support evidence-based decision making in public finance.',
    categoryPath: ['CIPFA', 'Services', 'CIPFAstats'],
    date: '2024-02-15',
    category: 'Service',
    tags: ['Data', 'Benchmarking', 'Statistics'],
    url: '/services/cipfastats',
    relevance: 7,
    readTime: '6 minute read',
    author: 'By CIPFA Data Team',
  },
  {
    title: 'Public Finance Magazine',
    description:
      "CIPFA's Public Finance Magazine provides in-depth analysis, news, and insights into public sector finance. Each issue covers key topics including local government finance, health finance, and public sector accounting standards.",
    categoryPath: ['CIPFA', 'Services', 'Publications'],
    date: '2024-01-10',
    category: 'Publication',
    tags: ['Magazine', 'News', 'Analysis'],
    url: '/services/public-finance-magazine',
    relevance: 6,
    readTime: '8 minute read',
    author: 'By Public Finance Editorial Team',
  },
  {
    title: 'Support for Audit Committees',
    description:
      'CIPFA provides comprehensive support for audit committees in public sector organisations. Our services include training, guidance, and best practice resources to help audit committees fulfil their governance and oversight responsibilities effectively.',
    categoryPath: ['CIPFA', 'Services', 'Audit Support'],
    date: '2023-12-05',
    category: 'Service',
    tags: ['Audit Committees', 'Governance', 'Best Practice'],
    url: '/services/audit-committee-support',
    relevance: 7,
    readTime: '5 minute read',
    author: 'By CIPFA Advisory Team',
  },
  {
    title: 'Tackling the Housing Crisis',
    description:
      'CIPFA works with local authorities and housing associations to address the housing crisis through financial analysis, strategic planning, and best practice guidance. Our resources help organisations develop sustainable housing strategies.',
    categoryPath: ['CIPFA', 'Services', 'Housing'],
    date: '2023-11-20',
    category: 'Service',
    tags: ['Housing', 'Local Government', 'Strategic Planning'],
    url: '/services/housing-crisis',
    relevance: 6,
    readTime: '7 minute read',
    author: 'By CIPFA Advisory Team',
  },
  {
    title: 'International Public Finance',
    description:
      'CIPFA provides international public finance services, supporting governments and public sector organisations worldwide. Our international work includes capacity building, technical assistance, and the development of public financial management standards.',
    categoryPath: ['CIPFA', 'Services', 'International'],
    date: '2023-10-15',
    category: 'Service',
    tags: ['International', 'Capacity Building', 'Standards'],
    url: '/services/international',
    relevance: 6,
    readTime: '6 minute read',
    author: 'By CIPFA International Team',
  },
];
